name: Next Build CI (pnpm)



on:

  pull_request:

    branches: [ '*' ]



  push:

    branches: [ 'main', 'dev' ]



jobs:

  build:


    runs-on: ubuntu-latest

    env:

      PNPM_DEBUG: 1



    steps:

      - name: Checkout repository

        uses: actions/checkout@v4

        with:

          fetch-depth: 0



      - name: Setup Node.js


        uses: actions/setup-node@v4

        with:

          node-version: '20'



      - name: Setup pnpm

        uses: pnpm/action-setup@v3

        with:

          version: 9

          run_install: false



      - name: Get pnpm store directory

        id: pnpm-cache

        shell: bash

        run: echo "store_path=$(pnpm store path --silent)" >> $GITHUB_OUTPUT



      - name: Setup pnpm cache


        uses: actions/cache@v4

        with:

          path: |

            ${{ steps.pnpm-cache.outputs.store_path }}

            node_modules

          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

          restore-keys: |

            ${{ runner.os }}-pnpm-



      - name: Check environment

        run: |

          echo "Directory contents:"

          ls -la

          echo "pnpm version:"

          pnpm --version

          echo "Node version:"

          node --version

          echo "Package.json content:"

          cat package.json

          if [ -f pnpm-lock.yaml ]; then

            echo "pnpm-lock.yaml found."

          else

            echo "WARNING: pnpm-lock.yaml not found. Consider committing it."

          fi



      - name: Install dependencies

        run: pnpm install --frozen-lockfile



      - name: Build App

        run: pnpm run build



      - name: Upload build artifact

        uses: actions/upload-artifact@v4

        with:

          name: next-build

          path: .next/

          retention-days: 7